import os
from dotenv import load_dotenv

load_dotenv()

PROXY_API_KEY = os.getenv("PROXY_API_KEY")

MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY")
MINIO_BUCKET = os.getenv("MINIO_BUCKET")
MINIO_SECURE = os.getenv("MINIO_SECURE")

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")

KAFKA_GROUP_IMAGE_WORKER = os.getenv("KAFKA_GROUP_IMAGE_WORKER")
KAFKA_TOPIC_IMAGE_RESPONSES = os.getenv("KAFKA_TOPIC_IMAGE_RESPONSES")
KAFKA_TOPIC_IMAGE_REQUESTS = os.getenv("KAFKA_TOPIC_IMAGE_REQUESTS")

STORAGE_SERVICE_URL = os.getenv("STORAGE_SERVICE_URL")

IMAGEWORKER_STORAGE_CLIENT_KEY = os.getenv("IMAGEWORKER_STORAGE_CLIENT_KEY")
