import os
from dotenv import load_dotenv

load_dotenv()

MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY")
MINIO_BUCKET = os.getenv("MINIO_BUCKET")
MINIO_SECURE = os.getenv("MINIO_SECURE", "False").lower() == "true"
MINIO_HOST = os.getenv("MINIO_HOST")
MINIO_PORT = os.getenv("MINIO_PORT")

IMAGEWORKER_STORAGE_CLIENT_KEY = os.getenv("IMAGEWORKER_STORAGE_CLIENT_KEY")
GATEWAY_STORAGE_CLIENT_KEY = os.getenv("GATEWAY_STORAGE_CLIENT_KEY")
WEBWAY_STORAGE_CLIENT_KEY = os.getenv("WEBWAY_STORAGE_CLIENT_KEY")

CALLER_KEYS = {
    "gateway": GATEWAY_STORAGE_CLIENT_KEY,
    "image_worker": IMAGEWORKER_STORAGE_CLIENT_KEY,
    "webway": WEBWAY_STORAGE_CLIENT_KEY
}
