import os
from dotenv import load_dotenv

load_dotenv()

PROXY_API_KEY = os.getenv("PROXY_API_KEY")

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")

KAFKA_GROUP_AI_WORKER = os.getenv("KAFKA_GROUP_AI_WORKER")
KAFKA_TOPIC_AI_REQUESTS = os.getenv("KAFKA_TOPIC_AI_REQUESTS")
KAFKA_TOPIC_AI_RESPONSES = os.getenv("KAFKA_TOPIC_AI_RESPONSES")

MEMORY_SERVICE_URL = os.getenv("MEMORY_SERVICE_URL")
MESSAGE_HISTORY_SERVICE_URL = os.getenv("MESSAGE_HISTORY_SERVICE_URL")