import os
from dotenv import load_dotenv

load_dotenv()

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")

KAFKA_GROUP_REACTION_WORKER = os.getenv("KAFKA_GROUP_REACTION_WORKER")

KAFKA_TOPIC_RAW_MESSAGES = os.getenv("KAFKA_TOPIC_RAW_MESSAGES")
KAFKA_TOPIC_CACHE_INVALIDATION = os.getenv("KAFKA_TOPIC_CACHE_INVALIDATION")

MEMORY_SERVICE_URL = os.getenv("MEMORY_SERVICE_URL")

REACTIONWORKER_MEMORY_CLIENT_KEY = os.getenv("REACTIONWORKER_MEMORY_CLIENT_KEY")

REACTIONWORKER_AUTOUPDATE_INTERVAL = int(os.getenv("REACTIONWORKER_AUTOUPDATE_INTERVAL", 300)) 