import os
from dotenv import load_dotenv

load_dotenv()

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")

REDIS_URL = os.getenv("REDIS_URL")

REDIS_PENDING_AI_PREFIX = os.getenv("REDIS_PENDING_AI_PREFIX")
REDIS_PENDING_IMAGE_PREFIX = os.getenv("REDIS_PENDING_IMAGE_PREFIX")
REDIS_PENDING_ADMIN_PREFIX = os.getenv("REDIS_PENDING_ADMIN_PREFIX")

PENDING_TTL_SECONDS = os.getenv("PENDING_TTL_SECONDS")

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")

KAFKA_GROUP_GATEWAY = os.getenv("KAFKA_GROUP_GATEWAY")
KAFKA_TOPIC_AI_REQUESTS = os.getenv("KAFKA_TOPIC_AI_REQUESTS")
KAFKA_TOPIC_AI_RESPONSES = os.getenv("KAFKA_TOPIC_AI_RESPONSES")
KAFKA_TOPIC_IMAGE_REQUESTS = os.getenv("KAFKA_TOPIC_IMAGE_REQUESTS")
KAFKA_TOPIC_IMAGE_RESPONSES = os.getenv("KAFKA_TOPIC_IMAGE_RESPONSES")
KAFKA_TOPIC_ADMIN_COMMANDS = os.getenv("KAFKA_TOPIC_ADMIN_COMMANDS")
KAFKA_TOPIC_ADMIN_RESPONSES = os.getenv("KAFKA_TOPIC_ADMIN_RESPONSES")
KAFKA_TOPIC_RAW_MESSAGES = os.getenv("KAFKA_TOPIC_RAW_MESSAGES")

KAFKA_TOPIC_REACTION_COMMANDS = os.getenv("KAFKA_TOPIC_REACTION_COMMANDS")

STORAGE_SERVICE_URL = os.getenv("STORAGE_SERVICE_URL")
MEMORY_SERVICE_URL = os.getenv("MEMORY_SERVICE_URL")

GATEWAY_MEMORY_CLIENT_KEY = os.getenv("GATEWAY_MEMORY_CLIENT_KEY")
GATEWAY_STORAGE_CLIENT_KEY = os.getenv("GATEWAY_STORAGE_CLIENT_KEY")
