import os
from dotenv import load_dotenv

load_dotenv()

KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")

KAFKA_TOPIC_ADMIN_COMMANDS = os.getenv("KAFKA_TOPIC_ADMIN_COMMANDS")
KAFKA_TOPIC_ADMIN_RESPONSES = os.getenv("KAFKA_TOPIC_ADMIN_RESPONSES")
KAFKA_GROUP_ADMIN_SERVICE = os.getenv("KAFKA_GROUP_ADMIN_SERVICE")

MEMORY_SERVICE_URL = os.getenv("MEMORY_SERVICE_URL")
SECURITY_SERVICE_URL = os.getenv("SECURITY_SERVICE_URL")