import os
from dotenv import load_dotenv

load_dotenv()

DISCORD_CLIENT_ID = os.getenv("DISCORD_CLIENT_ID")
DISCORD_CLIENT_SECRET = os.getenv("DISCORD_CLIENT_SECRET")
DISCORD_REDIRECT_URI = os.getenv("DISCORD_REDIRECT_URI")
DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
DISCORD_GUILD_ID = int(os.getenv("DISCORD_GUILD_ID", 0))
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", 60))
COOKIE_SECURE = os.getenv("COOKIE_SECURE", "false").lower() == "true"

WEBWAY_MEMORY_CLIENT_KEY = os.getenv("WEBWAY_MEMORY_CLIENT_KEY")
WEBWAY_SECURITY_CLIENT_KEY = os.getenv("WEBWAY_SECURITY_CLIENT_KEY")
WEBWAY_HISTORY_CLIENT_KEY = os.getenv("WEBWAY_HISTORY_CLIENT_KEY")
WEBWAY_STORAGE_CLIENT_KEY = os.getenv("WEBWAY_STORAGE_CLIENT_KEY")

MEMORY_SERVICE_URL = os.getenv("MEMORY_SERVICE_URL")
SECURITY_SERVICE_URL = os.getenv("SECURITY_SERVICE_URL")
STORAGE_SERVICE_URL = os.getenv("STORAGE_SERVICE_URL")
MESSAGE_HISTORY_SERVICE_URL = os.getenv("MESSAGE_HISTORY_SERVICE_URL")

PROXY_API_KEY = os.getenv("PROXY_API_KEY")

PROXY_API_BALANCE_URL = os.getenv("PROXY_API_BALANCE_URL")

REDIS_URL = os.getenv("REDIS_URL")

AUDIT_SERVICE_URL = os.getenv("AUDIT_SERVICE_URL", "http://audit_service:8006")
WEBWAY_AUDIT_CLIENT_KEY = os.getenv("WEBWAY_AUDIT_CLIENT_KEY")

AUDIT_FALLBACK_PATH = os.getenv("AUDIT_FALLBACK_PATH")
AUDIT_STREAM_KEY = os.getenv("AUDIT_STREAM_KEY", "/tmp/audit_fallback.jsonl")
AUDIT_STREAM_MAXLEN = int(os.getenv("AUDIT_STREAM_MAXLEN", "10000"))


KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")