import os
from dotenv import load_dotenv

load_dotenv()

POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")

REDIS_URL = os.getenv("REDIS_URL")

HISTORY_CACHE_LIMIT = os.getenv("HISTORY_CACHE_LIMIT")

REDIS_HISTORY_PREFIX = os.getenv("REDIS_HISTORY_PREFIX")

KAFKA_GROUP_MESSAGE_HISTORY = os.getenv("KAFKA_GROUP_MESSAGE_HISTORY")
KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")

KAFKA_TOPIC_RAW_MESSAGES = os.getenv("KAFKA_TOPIC_RAW_MESSAGES")

AIWORKER_HISTORY_CLIENT_KEY = os.getenv("AIWORKER_HISTORY_CLIENT_KEY")
WEBWAY_HISTORY_CLIENT_KEY = os.getenv("WEBWAY_HISTORY_CLIENT_KEY")

CALLER_KEYS = {
    "ai_worker": AIWORKER_HISTORY_CLIENT_KEY,
    "webway": WEBWAY_HISTORY_CLIENT_KEY
}
